name: YouTuBot

on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          NOSTR_PRIVKEY: ${{ secrets.NOSTR_PRIVKEY }}
          STACKER_USERNAME: ${{ secrets.STACKER_USERNAME }}
        run: npm start
